import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "Koggent",
        Title: data?.title || "Document",
        Creator: "Koggent",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    // title
    doc
      .fillColor("#111827")
      .fontSize(28)
      .text(data?.title || "Document", {
        align: "center",
      });

    // subtitle
    if (data?.subtitle) {
      doc.moveDown(0.5);
      doc
        .fillColor("#6B7280")
        .fontSize(12)
        .text(data.subtitle, {
          align: "center",
        });
    }

    doc.moveDown(2);

    if (Array.isArray(data?.sections)) {
      data.sections.forEach((s) => {
        if (s?.heading) {
          doc
            .fillColor("#111827")
            .fontSize(16)
            .text(s.heading, {
              align: "left",
            });

          doc.moveDown(0.5);
        }

        if (Array.isArray(s?.points)) {
          s.points.forEach((p) => {
            doc
              .fillColor("#374151")
              .fontSize(12)
              .text("•  " + String(p), {
                lineGap: 5,
              });
          });
        }

        doc.moveDown();
      });
    }

    // footer
    doc.moveDown();

    doc
      .fillColor("#9CA3AF")
      .fontSize(10)
      .text("Generated By Koggent", {
        align: "center",
      });

    doc.end();
  });
};
